# Generated by Django 4.1.3 on 2022-12-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='facultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputId', models.CharField(max_length=10)),
                ('inputName', models.CharField(max_length=100)),
                ('inputEmail', models.CharField(max_length=100)),
                ('inputEmployeeStatus', models.CharField(max_length=100)),
                ('inputCollege', models.CharField(max_length=100)),
                ('inputDepartment', models.CharField(max_length=100)),
                ('inputExpertiseSubject', models.CharField(max_length=300)),
                ('inputDayAvailability', models.CharField(max_length=100)),
                ('inputTimePreference', models.CharField(max_length=100)),
                ('inputUnitsLoad', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='chairmember',
            old_name='inputCollege',
            new_name='inputPassword',
        ),
        migrations.RenameField(
            model_name='chairmember',
            old_name='inputId',
            new_name='inputUsername',
        ),
        migrations.RemoveField(
            model_name='chairmember',
            name='inputDayAvailability',
        ),
        migrations.RemoveField(
            model_name='chairmember',
            name='inputDepartment',
        ),
        migrations.RemoveField(
            model_name='chairmember',
            name='inputEmail',
        ),
        migrations.RemoveField(
            model_name='chairmember',
            name='inputEmployeeStatus',
        ),
        migrations.RemoveField(
            model_name='chairmember',
            name='inputExpertiseSubject',
        ),
        migrations.RemoveField(
            model_name='chairmember',
            name='inputName',
        ),
        migrations.RemoveField(
            model_name='chairmember',
            name='inputTimePreference',
        ),
        migrations.RemoveField(
            model_name='chairmember',
            name='inputUnitsLoad',
        ),
    ]
