# Generated by Django 4.1.3 on 2022-12-03 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_facultymember_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chairMember',
        ),
        migrations.DeleteModel(
            name='facultyMember',
        ),
    ]
